update readme
andriy-baran/solidity-unittests-helpers pull request #1
Opened 2018-06-10 14:02 UTC by Zikot4

added 'readme' instruction
* Getting Started
* Prerequisites
* Installing
* Remove the package
* Versioning
* Quick Usage
* Authors
* License
* Contributing

2018-06-10 19:53 UTC, andriy-baran requested changes

2018-06-10 19:53 UTC, andriy-baran commented on README.md
> +
Please add yourself too

2018-06-10 19:58 UTC, Zikot4 commented on README.md
> +
ok, updated

2018-06-11 09:32 UTC, andriy-baran approved these changes

2018-06-11 09:33 UTC, merged